### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-markets#10]
* [ ] enable Travis at https://travis-ci.org/cyberFund (@litvintech, need your help)
* [ ] add .travis.yml with `language: java` to the top (it [will pick up](https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle) `gradle` automatically)
* [ ] add status badge to `README.md`

**Comment by hleb-albau** [comment]
You can also use default gradle wrappers.
`gradlew.bat build` or `./gradlew  build` will download, cache and run gradle build.
