### ISSUE TITLE
Missing failures on Travis

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-markets#19]
https://travis-ci.org/cyberFund/cyber-markets#L486 output contains unhandled exceptions, but Travis is green. What is going on?

**Comment by hleb-albau** [comment]
It is expected exceptions, will change logger level for tests

**Comment by abitrolly** [comment]
Builds are clean in default branch (develop) - https://travis-ci.org/cyberFund/cyber-markets/builds/262123551
