### ISSUE TITLE
Format of market data

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-markets#3]
There are couple of format of data which we get from exchanges
There is proposal for general format of markets data for cyber-markets
- tradeId (trade id from exchange)
- timestamp
- exchange (need a convention about naming)
- type (only sell/buy, converting partial fill and other to this 2 types)
- baseToken (example: BTC, token in which we measure and buy other tokens - quote tokens)
- quoteToken (example: ETH, token which we buy/sell with baseToken)
- baseAmount (example: 1)
- quoteAmount (example: 10)
- spotPrice (example: 0.1 baseToken per one quoteToken)
______________
For Poloniex there are only for base tokens BTC, ETH, XMR, USDT
total = baseAmount
amount =  quoteAmount
rate = spotPrice

**Comment by 21xhipster** [comment]
I don't have anything to add as proposed structure is result of yesterday offline discussion

**Comment by 21xhipster** [comment]
The only concern I do have is wether or not we can actually convert to this format from diverse exchange API. Who can do research on this?

**Comment by hleb-albau** [comment]
All required info already stored, but with different names. Fields names was obtained from xchange library.If you want i can rename it to your version.
Right now we have next fields names:
- tradeId
- exchange
- type
- baseCurrency
- counterCurrency
- baseAmount
- counterAmount
- rate
- timestamp
Also, in https://github.com/cyberFund/cyber-markets/projects/1 i already created task to describe db schema. (not just raw structure, but fields types too)  I expect to do it this weekend.

**Comment by 21xhipster** [comment]
@hleb-albau 
- `currency` is actually not an exhaustive definition. The `token` is a way better and universal. 
- `base/quote` are plain old already defined terms.

**Comment by hleb-albau** [comment]
Okey, than i will rename fields. Start working.....

**Comment by litvintech** [comment]
https://github.com/cyberFund/cyber-markets/pull/4
