### ISSUE TITLE
Build and run java applications in docker \w compose

### ISSUE THREAD

**Issue by IRus** [cyberFund/cyber-markets#32]
Using docker stages: build containers \w java. Run java applications in docker compose.

**Comment by abitrolly** [comment]
Multi-staged builds are cool - https://docs.docker.com/engine/userguide/eng-image/multistage-build/

If they can run on Ubuntu LTS docker - that will simplify things a lot.

**Comment by IRus** [comment]
I think this task done. @hleb-albau
