### ISSUE TITLE
[spark] create live time trades ticker calculation

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-markets#50]
Implement simple windowed algorithm for calculation tickers for **1h**, **3h**, **6h**, **24h** tickers with 5 sec precision.

Implementation variants:
1.  Using apache spark
2.  Own jvm implementation

- [ ]  Read kafka trades channels
- [ ]  Calculate tickers (for this task just hold all info in memory, no storage required)
- [ ]  Push tickers to kafka

**Comment by IRus** [comment]
Format:
`{lowestAsk, highestBid, percentChange, baseVolume, quoteVolume}`

Where:
* baseVolume - Sum of one currency
* quoteVolume - Sum of another currency
* lowestAsk -  Price of last lowest ask
* highestBid - Price of last highest bid
* percentChange - (avgPrice'/avgPrice)*100
