### ISSUE TITLE
Setup minimal dev/prod infrastructure environment

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-markets#52]
- [x] Setup minicube
- [x] Setup k8s
- [ ] Setup kafka
- [ ] Setup kafka manager
- [ ] Setup zookeeper
- [ ] Add documentation & bash script for bootstrap env

Use http://docs.confluent.io/current/cp-docker-images/docs/index.html images for:
kafka, zookeper

**Comment by abitrolly** [comment]
Instruction to setup `minukube` and `k8s` - https://github.com/cyberFund/cybernode/issues/82

**Comment by abitrolly** [comment]
What is the final result that I can validate?

**Comment by abitrolly** [comment]
For example, test for this issue - as a developer, after container is started, I get cluster IP and then to vaIidate that dev,environment works I should:

1. enter in command line ???

**Comment by abitrolly** [comment]
From the chat:
1. I connect to localhost:9000 (Kafka Manager UI) with browser
2. Go to cluster menu, add cluster, chose name and Zookeper

**Comment by abitrolly** [comment]
4. Start `connectors` app and `stream API` app

**Comment by hleb-albau** [comment]
5. Modify and open in browser https://github.com/cyberFund/cyber-markets/blob/development/stream-api/src/main/resources/trades-test.html

**Comment by abitrolly** [comment]
I should see appearing trades on this page.

**Comment by abitrolly** [comment]
Starting point - https://github.com/cyberFund/cyber-markets/tree/development/devops
