### ISSUE TITLE
Ethereum DEXs integration

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-markets#60]
[0x](https://github.com/0xProject/)
For trades needs to listen event **LogFill**:
[Exchange contract](https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol)

[EtherDelta](https://github.com/etherdelta)
[Exchange](https://etherdelta.github.io/)
For trades needs to listen event **Trade**
[Exchange contract](https://github.com/etherdelta/smart_contract/blob/master/etherdelta.sol)
https://coinmarketcap.com/exchanges/etherdelta/

[Java Ethereum Library](https://github.com/web3j/web3j)
One issue which we need to resolve - choose way of integration 
1. integration of connectors for dex's smart contracts to cyber-markets (which create dependency for whole cyber-markets to ethereum node)
2. side stand-alone services

**Comment by hleb-albau** [comment]
https://github.com/paritytech/parity/wiki/JSONRPC

**Comment by hleb-albau** [comment]
https://github.com/cyberFund/cybernode-connectors
