### ISSUE TITLE
Save trades to db

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-markets#71]
- [+]  Understand cassandra tables( partition key, composite key)
- [+]  Chose cassandra partition key for trades
- [+]  Chose cassandra composite key for trades
- [+]  Add  table difinition to devops/elassandra/bootstrap.cql

C* query examples.
select * from markets.trades where date=[date], exchange=[exchange1,exchange2], pair=[pair1,pair2]
select * from markets.trades where date=[date], exchange=[exchange1,exchange2]
select * from markets.trades where date=[date], pair=[pair1,pair2]

**Comment by litvintech** [comment]
Following my initial research I found the way which we can store our raw market data and tickers
There is InfluxDB, docs here
https://docs.influxdata.com/influxdb/v1.3/query_language/data_exploration/
just for example for our tickers 
<symbol, timestamp, open, high, low, close, volume>
Query is:
```
SELECT open, close FROM market_data_1m WHERE symbol = 'BTC' AND time > '2017-09-19 14:00' AND time < '2017-09-19 15:00'
```

**Comment by litvintech** [comment]
Java driver for influxdb
https://github.com/influxdata/influxdb-java

**Comment by hleb-albau** [comment]
read
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCreateTableTOC.html
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCompoundPrimaryKeyConcept.html

**Comment by hleb-albau** [comment]
See also https://docs.confluent.io/current/connect/index.html
See also http://docs.datamountaineer.com/en/latest/cassandra-sink.html
