### ISSUE TITLE
Ticker calculation

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-markets#96]
In this feature we are implementing ticker calculation with sliding window for set of time windows.
1. sliding window - 3 second, cause minimal block time now is 3 sec
2. windows - 1m, 5m, 15m, 30m, 1h, 3h, 6h, 12h, 24h
3. using kafka-streams

**Comment by litvintech** [comment]
https://github.com/gwenshap/kafka-streams-stockstats/blob/master/src/main/java/com/shapira/examples/streams/stockstats/StockStatsExample.java

**Comment by vstavetski** [comment]
@mgergalov @hleb-albau plese provide documentation how to build and run cyber-markets and poll trades from kafka topic

**Comment by vstavetski** [comment]
First steps - 5 minutes window with 3 seconds slide
- [ ] build and run cyber-markets
- [ ] calculate sum of base amount and quote amount for pair
- [ ] calculate price
- [ ] calculate quote volume 
- [ ] create stream to kafka topic

**Comment by vstavetski** [comment]
Next steps:
- [ ] add tickers calculations from from certain exchanges
- [ ] add stream api for tickers
